---
title: "Tests and Coverage"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
---

This output is created by [covrpage](https://github.com/yonicd/covrpage).

```{r load dependencies,include=FALSE}
library(covr     , warn.conflicts = FALSE , quietly = TRUE)
library(knitr    , warn.conflicts = FALSE , quietly = TRUE)
```

```{r run unit tests, include=FALSE}

test_x    <- testthat::test_check(
  package         = covrpage::package_name(path = '..'),
  reporter        = testthat::default_reporter(),
  stop_on_failure = FALSE,
  stop_on_warning = FALSE
)

skip <- length(test_x)>0
failed <- FALSE
```

```{r map tests, include=FALSE}
test_m <- covrpage::map_testthat('testthat')
```


```{r create summaries, include=FALSE}
test_x_short <- test_x |>
  covrpage::testthat_summary(type='short')

test_x_long <- test_x |>
  covrpage::testthat_summary(type='long')

```
 
```{r check for failed tests, include=FALSE,eval=skip}
test_skip <- test_x_long[test_x_long$status!='PASS',c('file','test')]

test_skip$file <- gsub('#(.*?)$','',basename(test_skip$file))

test_skip <- merge(test_skip,test_m)

failed <- any(test_x_long$status%in%c('ERROR','FAILED'))

```

```{r prep for skipped tests, include=FALSE,eval=!skip}

test_skip <- test_m

```

## Coverage

Coverage summary is created using the [covr](https://github.com/r-lib/covr) package.

```{r run covrage,include=FALSE}
if(any(grepl(covrpage::package_name(path = '..'),loadedNamespaces())))
  unloadNamespace(package_name(path = '..'))
cvr <- covrpage::coverage_skip(test_path = '../tests/testthat', test_skip = test_skip)
```

```{r message on coverage warning,echo=FALSE,eval=failed}
cat(sprintf('%s Not All Tests Passed\n  Coverage statistics are approximations of the non-failing tests.\n  Use with caution\n\n For further investigation check in testthat summary tables.',covrpage:::emos[[platform()]][['WARNING']]))
```

```{r summarize coverage,echo=FALSE}
cvr |>
  covrpage::covr_summary(failed = failed,package = package_name(path = '..')) |>
  knitr::kable(digits = 2,
             col.names = c('Object','Coverage (%)'),align = c('l','c'))

```

<br>

## Unit Tests

Unit Test summary is created using the [testthat](https://github.com/r-lib/testthat) package.

```{r print skipped warning for short summary,echo=FALSE,warning=FALSE,message=FALSE,eval=!skip}
cat('All tests were skipped')
```

```{r print short summary table,echo=FALSE,warning=FALSE,message=FALSE,eval=skip}

test_x_short |>
  knitr::kable()

```

<details `r sprintf('%s',if(skip) test_details(test_x_short))`>
  <summary> Show Detailed Test Results </summary>

```{r print skipped warning for long summary,echo=FALSE,warning=FALSE,message=FALSE,eval=!skip}
cat('All tests were skipped')
```

```{r print long summary table,echo=FALSE,warning=FALSE,message=FALSE,eval=skip}

test_x_long |>
  knitr::kable()

```

```{r prep session info summary table,echo=FALSE}
if(length(names(test_x_long))>0){
if('icon'%in%names(test_x_long)){
  emos <- covrpage:::emos[[covrpage:::platform()]]
  knitr::kable(t(c('Failed' = emos[['FAILED']],'Warning' = emos[['WARNING']], 'Skipped' = emos[['SKIPPED']])))
}  
}
```

</details>

<details>
  <summary> Session Info </summary>
  
```{r print session info summary table,echo=FALSE,warning=FALSE,message=FALSE}

x <- covrpage:::sinfo()

x$info |>
  knitr::kable()

x$pkgs |>
  knitr::kable()

```

</details>

`r sprintf('<!--- Final Status : %s --->', test_to_badge(test_x_short))`
